# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.50"
    hooks:
      - id: check-manifest
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
      - id: vulture
        name: vulture
        entry: vulture
        language: system
        types: [python]
        pass_filenames: false
      - id: bandit
        name: bandit
        entry: bandit -c pyproject.toml -r src
        language: system
        types: [python]
        pass_filenames: false
      - id: reuse
        name: reuse lint
        entry: reuse lint
        language: system
        pass_filenames: false
