# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: MPL-2.0

version = 1

[[annotations]]
path = ["README.md", "src/pyippdme/py.typed"]
SPDX-FileCopyrightText = "2026 Thomas Ascher <thomas.ascher@gmx.at>"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "src/pyippdme/schemas/*.xsd"
SPDX-FileCopyrightText = "VDMA e.V., Frankfurt/Main"
SPDX-License-Identifier = "LicenseRef-VDMA-8722"
