# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: MPL-2.0

# ruff: noqa: E501

"""The explanations behind :class:`~pyippdme.client.reference.CommandReference`.

These are short descriptions written for this package, in its own words: what a command does,
what its arguments mean and a typical call. They are not the text of the standard (VDMA 8722),
which has the exact definitions; read that for anything that matters.
"""

from __future__ import annotations

__all__ = ["ARGUMENTS", "ARGUMENT_OVERRIDES", "EXAMPLES", "NOTES", "RETURNS", "SUMMARIES"]

#: One line per command: what it does.
SUMMARIES: dict[str, str] = {
    # Session and errors
    "StartSession": "Open the session; the server resets its per-client settings to their defaults.",
    "EndSession": "Close the session and give the machine back to the server.",
    "AbortE": "Stop whatever the machine is doing right now (emergency abort of the motion).",
    "ClearAllErrors": "Acknowledge and clear every error the server has raised.",
    "GetErrStatusE": "Ask whether an error is active; answers even while errors block other commands.",
    "GetXtdErrStatus": "Report the error state in detail: homing state, active error number and severity.",
    "GetErrorInfo": "Look up the text and cause the server has for an error number.",
    "StopDaemon": "Stop one running report (a daemon started by an On...Report command) by its tag.",
    "StopAllDaemons": "Stop every report that is still running.",
    "EnumNameSpaces": "List the namespaces (company prefixes) of the extra commands this server has.",
    # Properties
    "GetProp": "Read one or more properties, for example Tool.Name() or Part.Approach().",
    "GetPropE": "Like GetProp, but also allowed while an error is active.",
    "SetProp": "Change a property, for example SetProp(Tool.PtMeasPar.Retract(5)).",
    "EnumProp": "List the properties directly under a reference such as Tool.",
    "EnumAllProp": "List all properties below a reference, including nested ones.",
    # Machine
    "GetDMEVersion": "Report which version of the I++ DME interface the server speaks.",
    "GetSupportedCommands": "List every command this server understands.",
    "GetSupportedArguments": "List the argument names and types one command accepts.",
    "GetMachineClass": "Report the machine class(es), e.g. a Cartesian CMM.",
    "Home": "Reference the machine axes so that positions are valid; usually needed before moving.",
    "IsHomed": "Ask whether the machine has been homed.",
    "EnableUser": "Let the program move the machine (the user enable switch).",
    "DisableUser": "Take the movement permission away again.",
    "IsUserEnabled": "Ask whether the program may move the machine.",
    "EnumerateMoverAxes": "List the axes the machine can move.",
    # Move
    "GoTo": "Move the tool to a position given as axis values, in a straight line.",
    "Step": "Move the tool by a distance relative to where it is.",
    "GoToOnCircle": "Move along a circular path around a centre to a target point.",
    "GoToOnSpiral": "Move along a spiral around a centre to a target point.",
    "Get": "Read the current value of axes or properties, for example Get(X(),Y(),Z()).",
    "OnMoveReport": "Start a report that sends positions while the machine moves, by time or distance.",
    "OnMoveReportE": "Like OnMoveReport, but also allowed while an error is active.",
    "LockAxis": "Keep an axis from moving in later moves.",
    "LockPosition": "Keep an axis at its current position in later moves.",
    # Coordinate systems
    "SetCoordSystem": "Choose the coordinate system that positions are given and reported in.",
    "GetCoordSystem": "Ask which coordinate system is active.",
    "SetCsyTransformation": "Place one coordinate system relative to its parent: offset and three angles.",
    "GetCsyTransformation": "Read how one coordinate system is placed relative to its parent.",
    "SaveNamedCsyTransformation": "Store a transformation under a name, kept across sessions.",
    "GetNamedCsyTransformation": "Read back a stored transformation by name.",
    "SaveActiveCoordSystem": "Store the placement of the part coordinate system under a name.",
    "LoadCoordSystem": "Restore a stored coordinate system and make it the part system.",
    "DeleteCoordSystem": "Remove a stored coordinate system.",
    "EnumCoordSystems": "List the names of the stored coordinate systems.",
    "EnableRotaryTableVarCsy": "Let the rotary table's own coordinate system follow its angle (or not).",
    "AlignPart": "Build the part coordinate system from measured points and direction vectors.",
    # Temperature
    "GetTemperatureSensors": "List the temperature sensors the machine has.",
    "ReadTemperatureSensor": "Read one temperature sensor by name.",
    "ReadAllTemperatures": "Read every temperature sensor.",
    "UpdateScaleTemperatures": "Take the scale temperatures from the sensors for the error compensation.",
    "SetScaleTemperatures": "Give the scale temperatures yourself, per axis.",
    "GetScaleTemperatures": "Read the scale temperatures that are being used.",
    "SetTemperatureCompensationOrigin": "Set the point from which thermal growth of the part is computed.",
    # Measure a point
    "OnPtMeasReport": "Choose what a PtMeas answers with: position, direction, quality and so on.",
    "PtMeas": "Measure one point: approach, probe the surface, report where it was touched.",
    "PtMeasPar": "Refer to the point measurement parameters (speed, approach, search, retract).",
    "PtMeasSelfCenter": "Measure a point where the probe finds the centre of a feature by itself.",
    "PtMeasSelfCenterLocked": "Self-centring measurement with the machine axes locked as set.",
    # Scan
    "OnScanReport": "Choose what each scan point is reported with: position, direction, and so on.",
    "ScanPar": "Refer to the scanning parameters (speed, acceleration).",
    "ScanOnLine": "Scan along a straight line between two points.",
    "ScanOnCircle": "Scan along a circular arc.",
    "ScanOnHelix": "Scan along a helix (an arc that also moves along its axis).",
    "ScanOnCurve": "Scan along a curve given as a list of points with their directions.",
    "ScanOnLineHint": "Tell the server how a line to be scanned may deviate from the nominal one.",
    "ScanOnCircleHint": "Tell the server how a circle to be scanned may deviate from the nominal one.",
    "ScanOnCurveHint": "Tell the server how far a curve may deviate and how sharp it bends.",
    "ScanOnCurveDensity": "Set how densely points are taken along a curve scan.",
    "ScanUnknownHint": "Give the smallest radius of curvature an unknown contour will have.",
    "ScanUnknownDensity": "Set how densely points are taken on an unknown contour.",
    "ScanInPlaneEndIsSphere": "Follow an unknown contour in a plane until the tool reaches a stop sphere.",
    "ScanInPlaneEndIsPlane": "Follow an unknown contour in a plane until it crosses a stop plane.",
    "ScanInPlaneEndIsCyl": "Follow an unknown contour in a plane until it enters a stop cylinder.",
    "ScanInCylEndIsSphere": "Follow an unknown contour around a cylinder until a stop sphere is reached.",
    "ScanInCylEndIsPlane": "Follow an unknown contour around a cylinder until a stop plane is crossed.",
    # Tool
    "Tool": "Refer to the active tool, e.g. as Tool.Name() inside GetProp.",
    "GoToPar": "Refer to the move parameters of the tool (speed, acceleration).",
    "OptPar": "Refer to the parameters of an optical tool.",
    "IsAlignable": "Ask whether the active tool can be turned (for example on an indexing head).",
    "AlignTool": "Turn the tool to point along a direction (and optionally a second one).",
    "AvrRadius": "Ask for the average radius of the tool tip.",
    "CalcToolAlignment": "Calculate the tool direction that belongs to given angles, without moving.",
    "CalcToolAngles": "Calculate the angles that belong to a given tool direction, without moving.",
    "UseSmallestAngletoAlignTool": "Choose whether aligning may turn an axis by 180 degrees or more.",
    "UseSmallestAngleToAlignTool": "The same command as UseSmallestAngletoAlignTool (the other spelling).",
    "ReQualify": "Qualify the active tool again on the reference sphere.",
    "EnableOptimize": "Let the server optimise the tool path for this tool.",
    "DisableOptimize": "Switch the path optimisation off.",
    "IsOptimizeEnabled": "Ask whether the path optimisation is on.",
    # Tool changer
    "EnumTools": "List the tools the machine has.",
    "ChangeTool": "Fetch a tool from the rack and mount it.",
    "FindTool": "Look for a tool and ask the server what it would do to change to it.",
    "FoundTool": "Ask which tool FindTool found.",
    "SetTool": "Tell the server that a tool is mounted, without changing anything.",
    "GetChangeToolAction": "Ask what the user has to do to change to a tool (a manual change).",
    "EnumToolCollection": "List the entries directly below a node of the tool collection.",
    "EnumAllToolCollections": "List every entry below a node of the tool collection.",
    "OpenToolCollection": "Open a node of the tool collection, for example to put a module in.",
    # Optical and raw data
    "DataAcquire": "Take a measurement with the optical tool and store it under a name.",
    "DeleteAcquistion": "Delete one stored acquisition.",
    "DeleteAcquisition": "The same command as DeleteAcquistion (the other spelling).",
    "DeleteAllAcquisitions": "Delete all stored acquisitions.",
    "AdvDataStruct": "Select the advanced data structure for acquisition results.",
    "RawDataBinSetup": "Set up the binary channel on which raw data is delivered.",
    "GetRawDataBin": "Send the raw data of an acquisition over the binary channel.",
    "GetRawDataShaMem": "Give the location of an acquisition's raw data in shared memory.",
    "ReleaseShaMem": "Free the shared memory that holds an acquisition's raw data.",
    "GetRawDataFile": "Give the file in which an acquisition's raw data was stored.",
    "DelRawDataFile": "Delete the raw data file of an acquisition.",
    # The deprecated class of regions and extraction
    "ROI": "Define a named region of interest for FeatureExtract (deprecated).",
    "FeatureExtract": "Fit a feature to the points of stored acquisitions inside regions of interest (deprecated).",
    # Form tester
    "CenterPart": "Centre a part on the form tester's rotary axis.",
    "TiltPart": "Tilt a part so that an axis is square to the rotary axis.",
    "TiltCenterPart": "Tilt and centre a part with two points on its axis.",
}

#: Longer remarks for the commands that need more than a line.
NOTES: dict[str, str] = {
    "GoTo": (
        "The arguments are axis values: X(10),Y(20). An axis you leave out stays where it is. "
        "R() turns the rotary table, and Tool.A/Tool.B or Tool.Alignment turn the tool. The move "
        "goes in a straight line; with Sync the program waits until the machine is there."
    ),
    "Step": "Same shape as GoTo, but every value is added to the present position.",
    "PtMeas": (
        "The tool goes to an approach position in front of the nominal point (along the probing "
        "direction IJK), searches for the surface at probing speed, takes the point when the probe "
        "triggers and moves away. The distances come from PtMeasPar. Without IJK the direction "
        "is taken from the last position to the nominal point. What comes back is set with "
        "OnPtMeasReport."
    ),
    "OnPtMeasReport": "Names the values a PtMeas returns, e.g. OnPtMeasReport(X,Y,Z,IJK).",
    "OnScanReport": "Names the values every scan point returns, e.g. OnScanReport(X,Y,Z).",
    "Home": "The machine moves to its reference marks; afterwards positions can be trusted.",
    "SetProp": "A property is written as Name(value); several can be given at once.",
    "GetProp": "A property is asked as Name() and answered as Name(value).",
    "SetCsyTransformation": (
        "Euler angles are Theta (0 to 180), Psi and Phi. The change lasts for this connection; "
        "use SaveNamedCsyTransformation to keep one."
    ),
    "AlignPart": (
        "Gives the part coordinate system from a point and a direction on each of two features, "
        "plus an optional rotary table angle."
    ),
    "ScanOnLine": "Points are returned as they are taken, in the format chosen by OnScanReport.",
    "ScanOnCircle": (
        "delta is the angle to run through; sfa is the angle between the start direction and the "
        "material (0 for the outside of a cylinder, 180 for the inside, 90 or 270 for a plane)."
    ),
    "ScanOnCurve": "The data is a list of points and directions in the given Format.",
    "ChangeTool": "The machine drives to the rack, puts the old module back and takes the new one.",
    "ROI": (
        'ROI("Name", Circle(...), include): the shape is a Line, Circle, Polygon2D, Cylinder, '
        "Sphere, Polygon3D or, relative to the feature, CircleRel, CylinderRel or SphereRel. "
        "include or exclude says whether the points inside count or not."
    ),
    "FeatureExtract": (
        "Acqs lists the acquisitions, the feature (Point, Line, Circle or Cylinder) gives the "
        "nominal position and direction, ROIs the regions. The report is GeoElem() for the fitted "
        "element or QEPs(S(step)) for the points that were used. The class is deprecated."
    ),
    "DataAcquire": (
        "The result is delivered through the raw data commands. Type says whether it is a point, "
        "a line or an area."
    ),
    "UseSmallestAngletoAlignTool": (
        "With flag 1 an alignment that would turn an axis by 180 degrees or more is refused "
        "with 2500. The default after StartSession is 0."
    ),
}

#: A typical call, where the plain signature is not enough.
EXAMPLES: dict[str, str] = {
    "GoTo": "GoTo(X(10),Y(20),Z(5))",
    "Step": "Step(Z(5))",
    "PtMeas": "PtMeas(X(10),Y(20),Z(0),IJK(0,0,1))",
    "OnPtMeasReport": "OnPtMeasReport(X(),Y(),Z(),IJK())",
    "OnScanReport": "OnScanReport(X(),Y(),Z())",
    "Get": "Get(X(),Y(),Z())",
    "GetProp": "GetProp(Tool.Name())",
    "SetProp": "SetProp(Tool.PtMeasPar.Retract(5))",
    "SetCoordSystem": "SetCoordSystem(PartCsy)",
    "SetCsyTransformation": "SetCsyTransformation(PartCsy,100,50,0,0,0,30)",
    "SaveActiveCoordSystem": 'SaveActiveCoordSystem("fixture-1")',
    "ChangeTool": 'ChangeTool("Probe 3mm")',
    "ROI": 'ROI("Around", Circle(50,40,5,0,0,1,1,0,0,15), include)',
    "FeatureExtract": 'FeatureExtract(Acqs("Ring"),Circle(50,40,5,0,0,1,1,0,0,10),ROIs("Around"),"S",GeoElem())',
    "ScanOnLine": "ScanOnLine(0,0,0,50,0,0,0,0,1,1)",
    "ScanOnCircle": "ScanOnCircle(0,0,0,10,0,0,0,0,1,360,0,2)",
    "GetErrorInfo": "GetErrorInfo(1006)",
    "UseSmallestAngletoAlignTool": "UseSmallestAngletoAlignTool(1)",
}

#: What an argument name usually means; ``ARGUMENT_OVERRIDES`` says it for one command.
ARGUMENTS: dict[str, str] = {
    "Positions": "Axis targets such as X(10),Y(20); axes left out do not move.",
    "Distances": "Axis distances such as X(5),Z(-2), added to the present position.",
    "Sync": "1 waits until the machine has arrived before the command completes.",
    "Axes": "The axes or properties to read or use, e.g. X,Y,Z or R.",
    "Parameters": "The values to include in the report, e.g. X,Y,Z,IJK.",
    "Properties": "One or more properties, written Name() to read or Name(value) to set.",
    "Reference": "The property path to list below, e.g. Tool.",
    "EventTag": "The tag of the report to stop, as it came with the report.",
    "ErrorNumber": "The error number to look up.",
    "CommandName": "The name of the command to ask about.",
    "Center": "The centre of the circle or spiral.",
    "IJK": "The direction (a vector, not necessarily of length 1).",
    "X": "Value of the X axis.",
    "Y": "Value of the Y axis.",
    "Z": "Value of the Z axis.",
    "R": "Angle of the rotary table.",
    "Time": "Time between reports in seconds.",
    "Dis": "Distance between reports in millimetres.",
    "Axis": "The axis to lock.",
    "Position": "The position, as axis values.",
    "Csy": "Name of a coordinate system of the chain, e.g. MachineCsy or PartCsy.",
    "Name": "A name, in quotes, for a stored coordinate system or a sensor.",
    "X0": "X offset of the origin from the parent system.",
    "Y0": "Y offset of the origin from the parent system.",
    "Z0": "Z offset of the origin from the parent system.",
    "Theta": "Second Euler angle in degrees, 0 to 180.",
    "Psi": "Third Euler angle in degrees.",
    "Phi": "First Euler angle in degrees.",
    "Bool": "1 to switch on, 0 to switch off.",
    "Flag": "1 to switch on, 0 to switch off.",
    "px1": "X of the point on the first feature.",
    "py1": "Y of the point on the first feature.",
    "pz1": "Z of the point on the first feature.",
    "mx1": "X of the direction of the first feature.",
    "my1": "Y of the direction of the first feature.",
    "mz1": "Z of the direction of the first feature.",
    "px2": "X of the point on the second feature.",
    "py2": "Y of the point on the second feature.",
    "pz2": "Z of the point on the second feature.",
    "mx2": "X of the direction of the second feature.",
    "my2": "Y of the direction of the second feature.",
    "mz2": "Z of the direction of the second feature.",
    "alpha": "Allowed angular deviation, or the angle to turn, in degrees.",
    "beta": "A second angle, in degrees.",
    "Temperatures": "Scale temperatures per axis, e.g. X(20.1),Y(20.3).",
    "Sx": "X of the start point.",
    "Sy": "Y of the start point.",
    "Sz": "Z of the start point.",
    "Ex": "X of the end point (or of the stop sphere centre).",
    "Ey": "Y of the end point (or of the stop sphere centre).",
    "Ez": "Z of the end point (or of the stop sphere centre).",
    "i": "I component of the probing direction.",
    "j": "J component of the probing direction.",
    "k": "K component of the probing direction.",
    "StepW": "Distance (or angle, for arcs) between scan points.",
    "RT": "1 lets the rotary table move during the scan.",
    "Cx": "X of the circle or cylinder axis point.",
    "Cy": "Y of the circle or cylinder axis point.",
    "Cz": "Z of the circle or cylinder axis point.",
    "delta": "Angle to scan through, in degrees.",
    "sfa": "Surface angle: 0 outside of a cylinder, 180 inside, 90 or 270 a plane.",
    "pitch": "Advance along the axis for one turn of the helix.",
    "Closed": "1 if the curve ends where it starts.",
    "Format": "The layout of the points in Data (positions, directions, rotary angle).",
    "Data": "The curve points in the layout given by Format.",
    "Angle": "Largest angle between neighbouring scan points in degrees.",
    "AngleBaseLength": "Chord length the angle limit refers to.",
    "AtNominals": "1 takes points at the nominal points of the curve.",
    "Displacement": "Allowed offset of the circle centre.",
    "Form": "Allowed form deviation.",
    "Deviation": "Allowed deviation from the nominal curve.",
    "MinRadiusOfCurvature": "Smallest radius of curvature on the contour.",
    "Si": "I of the probing direction at the start.",
    "Sj": "J of the probing direction at the start.",
    "Sk": "K of the probing direction at the start.",
    "Ni": "I of the normal of the scanning plane.",
    "Nj": "J of the normal of the scanning plane.",
    "Nk": "K of the normal of the scanning plane.",
    "Dx": "X of the point that shows the direction to scan in.",
    "Dy": "Y of the point that shows the direction to scan in.",
    "Dz": "Z of the point that shows the direction to scan in.",
    "Dia": "Diameter of the stop sphere.",
    "n": "How many times the stop element has to be reached.",
    "Ei": "I of the probing direction at the end.",
    "Ej": "J of the probing direction at the end.",
    "Ek": "K of the probing direction at the end.",
    "Px": "X of a point on the stop plane.",
    "Py": "Y of a point on the stop plane.",
    "Pz": "Z of a point on the stop plane.",
    "Pi": "I of the stop plane's normal.",
    "Pj": "J of the stop plane's normal.",
    "Pk": "K of the stop plane's normal.",
    "Ci": "I of the cylinder axis direction.",
    "Cj": "J of the cylinder axis direction.",
    "Ck": "K of the cylinder axis direction.",
    "d": "Diameter of the stop cylinder.",
    "i1": "I of the first direction the tool is to point along.",
    "j1": "J of the first direction the tool is to point along.",
    "k1": "K of the first direction the tool is to point along.",
    "i2": "I of the second direction (fixes the turn about the first).",
    "j2": "J of the second direction.",
    "k2": "K of the second direction.",
    "Alignment": "The tool direction as numbers, e.g. Tool.Alignment(0,0,1).",
    "ToolName": "Name of the tool, in quotes.",
    "NodeName": "Name of a node of the tool collection, with dots between levels.",
    "AcqName": "Name of the acquisition.",
    "Type": "Kind of acquisition: point, line or area data.",
    "AcquiseSettingsName": "Name of a saved set of acquisition settings.",
    "RawDataFormat": "How raw data is delivered, e.g. the shared memory or binary format.",
    "Port": "TCP port of the binary channel.",
    "LiveMode": "Whether raw data is sent while the acquisition runs.",
    "Px1": "X of the first point on the part axis.",
    "Py1": "Y of the first point on the part axis.",
    "Pz1": "Z of the first point on the part axis.",
    "Px2": "X of the second point on the part axis.",
    "Py2": "Y of the second point on the part axis.",
    "Pz2": "Z of the second point on the part axis.",
    "Limit": "Largest allowed run-out; the routine stops when it is reached.",
}

#: Meaning of an argument for one command, where the general text does not fit.
ARGUMENT_OVERRIDES: dict[tuple[str, str], str] = {
    ("GoToOnCircle", "X"): "X of the target point on the circle.",
    ("GoToOnCircle", "Y"): "Y of the target point on the circle.",
    ("GoToOnCircle", "Z"): "Z of the target point on the circle.",
    ("GoToOnSpiral", "X"): "X of the target point on the spiral.",
    ("GoToOnSpiral", "Y"): "Y of the target point on the spiral.",
    ("GoToOnSpiral", "Z"): "Z of the target point on the spiral.",
    ("GoToOnCircle", "IJK"): "The direction of the circle's axis.",
    ("GoToOnSpiral", "IJK"): "The direction of the spiral's axis.",
    ("LockPosition", "Position"): "The axis position to hold, e.g. Z(10).",
    ("SetTemperatureCompensationOrigin", "X"): "X of the origin.",
    ("SetTemperatureCompensationOrigin", "Y"): "Y of the origin.",
    ("SetTemperatureCompensationOrigin", "Z"): "Z of the origin.",
    ("PtMeasSelfCenter", "Position"): "The nominal position and direction of the feature.",
    ("PtMeasSelfCenterLocked", "Position"): "The nominal position and direction of the feature.",
    ("CalcToolAlignment", "Axes"): "The tool angles, e.g. Tool.A(30),Tool.B(45).",
    ("ScanInPlaneEndIsPlane", "n"): "How many times the stop plane has to be crossed.",
    ("ScanInCylEndIsPlane", "n"): "How many times the stop plane has to be crossed.",
    ("ScanInPlaneEndIsCyl", "n"): "How many times the stop cylinder has to be entered.",
    ("ScanInPlaneEndIsSphere", "n"): "How many times the stop sphere has to be entered.",
    ("ScanInCylEndIsSphere", "n"): "How many times the stop sphere has to be entered.",
    ("ScanInCylEndIsSphere", "Cx"): "X of a point on the cylinder axis.",
    ("ScanInCylEndIsSphere", "Cy"): "Y of a point on the cylinder axis.",
    ("ScanInCylEndIsSphere", "Cz"): "Z of a point on the cylinder axis.",
    ("ScanInCylEndIsPlane", "Cx"): "X of a point on the cylinder axis.",
    ("ScanInCylEndIsPlane", "Cy"): "Y of a point on the cylinder axis.",
    ("ScanInCylEndIsPlane", "Cz"): "Z of a point on the cylinder axis.",
    ("ScanInPlaneEndIsCyl", "Cx"): "X of a point on the stop cylinder's axis.",
    ("ScanInPlaneEndIsCyl", "Cy"): "Y of a point on the stop cylinder's axis.",
    ("ScanInPlaneEndIsCyl", "Cz"): "Z of a point on the stop cylinder's axis.",
    ("ScanOnLineHint", "Angle"): "Allowed angular deviation of the line.",
    ("ScanOnLineHint", "Form"): "Allowed form deviation of the line.",
    ("CenterPart", "Px"): "X of the nominal centre point.",
    ("CenterPart", "Py"): "Y of the nominal centre point.",
    ("CenterPart", "Pz"): "Z of the nominal centre point.",
    ("TiltPart", "Dx"): "X of the direction to square up.",
    ("TiltPart", "Dy"): "Y of the direction to square up.",
    ("TiltPart", "Dz"): "Z of the direction to square up.",
    ("EnumToolCollection", "NodeName"): "The node whose direct entries are listed.",
    ("EnumAllToolCollections", "NodeName"): "The node whose entries, at all levels, are listed.",
    ("DataAcquire", "n"): "How many positions or frames the acquisition covers.",
    ("GetErrorInfo", "ErrorNumber"): "The error number, e.g. 1006.",
    ("SaveActiveCoordSystem", "Name"): "The name to store the active part system under.",
    ("LoadCoordSystem", "Name"): "The stored system to restore.",
    ("DeleteCoordSystem", "Name"): "The stored system to remove.",
    ("GetNamedCsyTransformation", "Name"): "The stored transformation to read.",
    ("SaveNamedCsyTransformation", "Name"): "The name to store the transformation under.",
    ("ReadTemperatureSensor", "Name"): "The sensor to read.",
}

_NOTHING = "Nothing; the command only completes (or fails with an error)."

#: What a command answers with, where it is clear. A command that is not listed is unknown here.
RETURNS: dict[str, str] = {
    **dict.fromkeys(
        (
            "StartSession",
            "EndSession",
            "AbortE",
            "ClearAllErrors",
            "StopDaemon",
            "StopAllDaemons",
            "SetProp",
            "Home",
            "EnableUser",
            "DisableUser",
            "GoTo",
            "Step",
            "GoToOnCircle",
            "GoToOnSpiral",
            "LockAxis",
            "LockPosition",
            "SetCoordSystem",
            "SetCsyTransformation",
            "SaveNamedCsyTransformation",
            "SaveActiveCoordSystem",
            "LoadCoordSystem",
            "DeleteCoordSystem",
            "EnableRotaryTableVarCsy",
            "UpdateScaleTemperatures",
            "SetScaleTemperatures",
            "SetTemperatureCompensationOrigin",
            "OnPtMeasReport",
            "OnScanReport",
            "ScanOnLineHint",
            "ScanOnCircleHint",
            "ScanOnCurveHint",
            "ScanOnCurveDensity",
            "ScanUnknownHint",
            "ScanUnknownDensity",
            "ChangeTool",
            "SetTool",
            "ReQualify",
            "EnableOptimize",
            "DisableOptimize",
            "UseSmallestAngletoAlignTool",
            "UseSmallestAngleToAlignTool",
            "DeleteAcquistion",
            "DeleteAcquisition",
            "ROI",
            "DeleteAllAcquisitions",
            "ReleaseShaMem",
            "DelRawDataFile",
            "RawDataBinSetup",
        ),
        _NOTHING,
    ),
    "GetErrStatusE": "The error state: whether an error is active.",
    "GetXtdErrStatus": "Whether the machine is homed and, if an error is active, its number and severity.",
    "GetErrorInfo": "The name and description of the error.",
    "EnumNameSpaces": "The namespace prefixes of the extra commands.",
    "GetProp": "Every property asked for, as Name(value).",
    "GetPropE": "Every property asked for, as Name(value).",
    "EnumProp": "The names of the properties directly below the reference.",
    "EnumAllProp": "The names of all properties below the reference.",
    "GetDMEVersion": "The version of the interface the server speaks.",
    "GetSupportedCommands": "The name of every command the server knows.",
    "GetSupportedArguments": "Each argument of the command with its type.",
    "GetMachineClass": "The name of the machine class (or classes).",
    "IsHomed": "1 if the machine is homed, otherwise 0.",
    "IsUserEnabled": "1 if the program may move the machine, otherwise 0.",
    "EnumerateMoverAxes": "The names of the axes the machine can move.",
    "Get": "Every value asked for, as Name(value), e.g. X(10.5),Y(3).",
    "OnMoveReport": "Nothing at first; position reports then arrive as events until the report is stopped.",
    "OnMoveReportE": "Nothing at first; position reports then arrive as events until the report is stopped.",
    "GetCoordSystem": "The name of the active coordinate system.",
    "GetCsyTransformation": "The placement as X0, Y0, Z0, Theta, Psi and Phi.",
    "GetNamedCsyTransformation": "The stored placement as X0, Y0, Z0, Theta, Psi and Phi.",
    "EnumCoordSystems": "The names of the stored coordinate systems.",
    "GetTemperatureSensors": "The sensors, each with its name and kind.",
    "ReadTemperatureSensor": "The temperature of the sensor in degrees Celsius.",
    "ReadAllTemperatures": "The temperature of every sensor.",
    "GetScaleTemperatures": "The scale temperature of each axis asked for.",
    "PtMeas": "The values chosen with OnPtMeasReport; by default X, Y and Z of the touched point.",
    "PtMeasSelfCenter": "The values chosen with OnPtMeasReport for the found point.",
    "ScanOnLine": "The scan points, in the format of OnScanReport, as the machine takes them.",
    "ScanOnCircle": "The scan points, in the format of OnScanReport, as the machine takes them.",
    "ScanOnHelix": "The scan points, in the format of OnScanReport, as the machine takes them.",
    "ScanOnCurve": "The scan points, in the format of OnScanReport, as the machine takes them.",
    "ScanInPlaneEndIsSphere": "The scan points up to the stop element, in the format of OnScanReport.",
    "ScanInPlaneEndIsPlane": "The scan points up to the stop element, in the format of OnScanReport.",
    "ScanInPlaneEndIsCyl": "The scan points up to the stop element, in the format of OnScanReport.",
    "ScanInCylEndIsSphere": "The scan points up to the stop element, in the format of OnScanReport.",
    "ScanInCylEndIsPlane": "The scan points up to the stop element, in the format of OnScanReport.",
    "IsAlignable": "1 if the tool can be turned, otherwise 0.",
    "AlignTool": "The direction vector(s) the tool reached.",
    "AvrRadius": "The average radius of the tool tip in millimetres.",
    "CalcToolAlignment": "The direction vector(s) that belong to the angles; nothing moves.",
    "CalcToolAngles": "The angles that belong to the direction; nothing moves.",
    "IsOptimizeEnabled": "1 if the path optimisation is on, otherwise 0.",
    "EnumTools": "The names of the tools.",
    "FoundTool": "The name of the tool FindTool found.",
    "GetChangeToolAction": "What has to be done to change to the tool, and where.",
    "EnumToolCollection": "The entries of the node, each with its kind (Collection or Tool) and name.",
    "EnumAllToolCollections": "The entries of the node at all levels, with kind and name.",
    "OpenToolCollection": "The entries of the node that was opened.",
    "DataAcquire": "Nothing until the acquisition is done; fetch the data with one of the raw data commands.",
    "GetRawDataBin": "The raw data, over the binary channel set up with RawDataBinSetup.",
    "GetRawDataShaMem": "Where the raw data is in shared memory: offset and size.",
    "GetRawDataFile": "The URL of the file with the raw data.",
    "FeatureExtract": "With GeoElem the fitted element, written like its own definition; with QEPs the points used.",
}
